apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: dvin/otus-gcp-frontend:1.0.2
        env:
        - name: AD_SERVICE_ADDR
          value: "localhost:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "localhost:3550"
        - name: CHECKOUT_SERVICE_ADDR
          value: "localhost:3550"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "localhost:3550"
        - name: CART_SERVICE_ADDR
          value: "localhost:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "localhost:3550"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "localhost:3550"
