apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: dvin/otus-gcp-frontend:1.0.1
    name: frontend
    resources: {}
    env:
    - name: AD_SERVICE_ADDR
      value: "localhost:3550"
    - name: SHIPPING_SERVICE_ADDR
      value: "localhost:3550"
    - name: CHECKOUT_SERVICE_ADDR
      value: "localhost:3550"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "localhost:3550"
    - name: CART_SERVICE_ADDR
      value: "localhost:3550"
    - name: CURRENCY_SERVICE_ADDR
      value: "localhost:3550"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "localhost:3550"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
